name: publish-report

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  print-hello-python:
    name: json Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: pip3 install --user requests beautifulsoup4 pandas
    - run: python python/football.py
    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          mv TextFootball.json python/TextFootball.json
          git add python/TextFootball.json
          git commit -m "update json"|| echo "Nothing to update"
          git push
    
  
  publish-quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::rjson
            any::tidyverse
            any::echarts4r
            

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: my_report_quarto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
