name: publish-report

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  print-hello-python:
    name: json Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: pip3 install --user requests beautifulsoup4 re pandas
    - run: python python/football.py


