name: publish-report

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  print-hello-python:
    name: json Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: pip3 install --user requests beautifulsoup4 pandas
    - run: python python/football.py
    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          mv TextFootball.json python/TextFootball.json
          git add python/TextFootball.json
          git commit -m "update json"
          git push
          
